name: djaaja_siha
description: "Chicken AI app for detection and classification of chicken diseases"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  connectivity: ^3.0.6
  camera: ^0.10.5+9
  path_provider: ^2.1.2
  path: ^1.9.0
  image_picker: ^0.8.6
  image_cropper: ^3.0.1
  permission_handler: ^11.3.0
  flutter_localizations:
    sdk: flutter
  intl: any
  shared_preferences: ^2.0.13
  flutter_tflite: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/sick_logo.png
    - assets/healthy_logo.png
    - assets/labels.txt
    - assets/densenet_model.tflite
 

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
