// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmdoGGLT-9iXkpHcVDAwAe9xH5MDgtZtQ',
    appId: '1:219694789124:web:1dc299b3faa882cb5bfb51',
    messagingSenderId: '219694789124',
    projectId: 'chicken-ai-7d8a3',
    authDomain: 'chicken-ai-7d8a3.firebaseapp.com',
    storageBucket: 'chicken-ai-7d8a3.appspot.com',
    measurementId: 'G-0BY1ZD9FKB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWFCVbj7zqLQ7Vj1cixc77-NUD3XcZSS4',
    appId: '1:219694789124:android:3c349a050cf21b085bfb51',
    messagingSenderId: '219694789124',
    projectId: 'chicken-ai-7d8a3',
    storageBucket: 'chicken-ai-7d8a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4PiKICIk4WSygSJDLR_p8rTXDiPtxqDY',
    appId: '1:219694789124:ios:4627c977750a95415bfb51',
    messagingSenderId: '219694789124',
    projectId: 'chicken-ai-7d8a3',
    storageBucket: 'chicken-ai-7d8a3.appspot.com',
    iosBundleId: 'com.example.djaajaSiha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4PiKICIk4WSygSJDLR_p8rTXDiPtxqDY',
    appId: '1:219694789124:ios:4627c977750a95415bfb51',
    messagingSenderId: '219694789124',
    projectId: 'chicken-ai-7d8a3',
    storageBucket: 'chicken-ai-7d8a3.appspot.com',
    iosBundleId: 'com.example.djaajaSiha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmdoGGLT-9iXkpHcVDAwAe9xH5MDgtZtQ',
    appId: '1:219694789124:web:7dae59dfa1149fed5bfb51',
    messagingSenderId: '219694789124',
    projectId: 'chicken-ai-7d8a3',
    authDomain: 'chicken-ai-7d8a3.firebaseapp.com',
    storageBucket: 'chicken-ai-7d8a3.appspot.com',
    measurementId: 'G-17WTKFZEBZ',
  );
}
